### ISSUE TITLE
Why did you steal GamerPablito's code?

### ISSUE THREAD

**Issue by Eventretta** [obamacat3/OBAMACAT-STUFF#1]
You stealed the GameJolt library from @GamerPablito

1) Stealing code is illegal
2) He put alot of errot, why stealing it?

He might also confirm, i'm sending him the issue link.

**Comment by GamerPablito** [comment]
Eventy, it's not the GameJolt thingie, it's an FNF language installer (that I have in GameBanana only), it's a batch file for that stuff.

But anyways, mister Obamacat3, I don't agree you post my stuff publicly without my permission!

**Comment by GamerPablito** [comment]
@obamacat3 do not ignore me anymore, you will regret it...

**Comment by obamacat3** [comment]
@GamerPablito i already addressed this with him i wasnt stealing it i was sharing it i never claimed it as mine lol dont witch hunt!
its already taken down too

**Comment by obamacat3** [comment]
@GamerPablito i already addressed this with him i wasnt stealing it i was sharing it i never claimed it as mine lol dont witch hunt!
its already taken down too

**Comment by GamerPablito** [comment]
@obamacat3 No it's not, it's just outdated

So, why in your README.md it says you're sharing YOUR stuff?

**Comment by obamacat3** [comment]
@GamerPablito idk what your denying
i never said it was all made by me
most stuff here is just for archiving

**Comment by GamerPablito** [comment]
![Screenshot_20221025-212007__01.jpg](https://user-images.githubusercontent.com/90533702/197926910-53c84348-8c7f-4074-97c0-446e0f90e63f.jpg)

**Comment by GamerPablito** [comment]
@obamacat3 Ok, you're right, I admit it.
I overreacted a bit, but then try to be specific in that file.

Put something like: "I'm sharing some stuff I DOWNLOADED" instead of "I'm sharing MY assets", cuz it can create some unexpected confusions.

It's for your own sake!

(Also, the info about your Discord seems like it's outdated)

**Comment by obamacat3** [comment]
@GamerPablito  you got your definitions wrong!
im not gonna explain it to you and im certaintly not gonna have a shouting match

**Comment by obamacat3** [comment]
ok glad this is over

**Comment by GamerPablito** [comment]
@obamacat3 Sorry for all the inconvenience I made against you by here and by Twitter, but please, take the right measure about I just told you, alright?

**Comment by GamerPablito** [comment]
Ok, won't bother you anymore, see ya

**Comment by GamerPablito** [comment]
@Eventretta You can close this now, it's everything settled in peace :)
